language: python
python:
- 3.8
- 3.7
- 3.6
- 3.5
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: kGN2jx3CkPP1WrrD7EmkBhjpot+rNCfK68462041+S3c2VMTcJF4+TMY9Rw4ypfNjz3M/v2D4RTyPuV/T2L5xEEmeviiMvUs+mOu90+I55FRVPKt3pemsZfHrhyRoFNkOjS7b1jqG1cpQVU/MxJkcWlJ15M/Xve5TdRhk9COKEA83IrbVEPnT1G9J9ET91i5NtCumzlvJNH4Sy+28kTmz6DYTQyKHaXrJsH73BJrNHUlWh23v1LOahfOWggWusREWnb1TNeMyQyWYzXEDtBzqvkdDQXifWOzOxGAZzTqKrHRuEAzUV6FxlbiGIKapjfvSrItQLElCnvKh2T46A9kae7WCF/Q6qs5hB/8qzGHR4pJUEbiiJZLxILZpdh3lH6SKoZWgZBZsk8Ndo7qbRIq6w0cLeFDCtia/d4IWzlfEiWhM04ey6TuxU7VsZVzu0bTrqqAY4o9/AKmXgEszcJlQwtOt6zT4OYfY6cDS2/uwPpDlMd68EhwuyF4kowkq3jYTr01dPv3j2vuFKTCbW9xJBj+p0n31BI4XjHkiI5HUAmo/3FNEpLskJDgQDT9AopRnlkTMfhqbborcEjst4zcUyHWr+30AwgfMi1I8Fd/KIO8pbly9fnqN67g1eduZpDDhOc6QXKLCI1diVy4mfxZFFMvOU1mplKv/P5vVveUmEI=
  on:
    tags: true
    repo: gmagno/spyci
    python: 3.8
